config/routes.rb
ReadIt::Application.routes.draw do

    resources :books do |book|
      resources :reviews, :only => :create
    end

    resource :admin_session
    resource :user_session
    resources :users

  root :controller => "books", :action => "index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation, :avatar
  acts_as_authentic
end

app/models/admin_session.rb
class AdminSession < Authlogic::Session::Base
  # attr_accessible :title, :body
   def to_key 
    new_record? ? nil : [ self.send(self.class.primary_key) ] 
   end 
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews
  attr_accessible :author, :description, :title, :cover_image
  has_attached_file :cover_image, :styles => { :medium => "300x300>" }

  validates_attachment_size :cover_image, :less_than => 5.megabytes
  validates_attachment_content_type :cover_image,
                                    :content_type => ['image/jpg', 'image/jpeg', 'image/gif', 'image/png']
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
  attr_accessible :author, :rating, :text
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :reviews
  attr_accessible :username, :email, :first_name, :last_name,
  				  :password, :password_confirmation, :avatar
  acts_as_authentic

  has_attached_file :avatar, :styles => { :small => "150x150>" },
				    :default_url => "/images/:style/missing.jpg"

  validates_attachment_size :avatar, :less_than => 5.megabytes
  validates_attachment_content_type :avatar,
                                    :content_type => ['image/jpg', 'image/jpeg', 'image/gif', 'image/png']

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # attr_accessible :title, :body
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController    
  def new  
    @admin_session = AdminSession.new  
  end  
  
  def create  
    @admin_session = AdminSession.new(params[:admin_session])  
    if @admin_session.save  
      flash[:notice] = "Admin login successful!"  
      redirect_to books_path  
    else  
      render :action => :new  
    end  
  end  
  
  def destroy  
    current_admin_session.destroy  
    flash[:notice] = "Admin logout successful!"  
    redirect_to books_path  
  end  
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery

  helper_method :admin?, :current_admin_session, :current_admin, :current_user, :current_user_session
  
  private  

  def current_admin_session  
    return @current_admin_session if defined?(@current_admin_session)  
    @current_admin_session = AdminSession.find  
  end  
  
  def current_admin  
    return @current_admin if defined?(@current_admin)  
    @current_admin = (current_admin_session && current_admin_session.admin)
  end  

  def current_user_session
    return @current_user_session if defined?(@current_user_session)  
    @current_user_session = UserSession.find  
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = (current_user_session && current_user_session.user) || (current_admin_session && current_admin_session.admin)
  end

end  

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_filter :admin_required, :only => [:new, :edit, :destroy]
	before_filter :login_required, :except => [:index, :show]

	def index
		@books = Book.paginate(:page => params[:page], :per_page => 10)
	end

	def show
		@book = Book.find params[:id]
		@reviews = @book.reviews
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new params[:book]
		if @book.save
			flash[:notice] = "#{@book.title} saved"
			redirect_to @book
		else
			render :new
		end
	end

	def edit
		@book = Book.find params[:id]
	end

	def update
		@book = Book.find params[:id]
		if @book.update_attributes(params[:book])
			flash[:notice] = "#{@book.title} saved"
			redirect_to @book
		else
			render :edit
		end
	end

	def destroy
		book = Book.find params[:id]  
		book.destroy  
		flash[:notice] = "#{book.title} deleted."  
		redirect_to books_path  
	end  

	private
	def admin_required
		unless current_admin
			flash[:error] = "Only logged in admins can access this page"
			redirect_to books_path
		end
	end

	def login_required
		unless current_user
			flash[:error] = "Must be logged in to view this page"
			redirect_to books_path
		end
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create
		book = Book.find params[:book_id]
		review = book.reviews.new params[:review]
		review.save
		flash[:notice] = "Review saved"
		redirect_to book_path(book)
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	def new  
	  @user_session = UserSession.new  
	end  

	def create
		@user_session = UserSession.new(params[:user_session])
		if @user_session.save
			flash[:notice] = "Successfully logged in."
			redirect_to root_url
		else
			render :new
		end
	end

	def destroy
		@user_session = UserSession.find
		@user_session.destroy
		flash[:notice] = "Successfully logged out."
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :login_required, :except => [:index, :new, :create]

	def index
		@users = User.all
	end

	def show
		@user = User.find params[:id]
		@reviews = @user.reviews
		@books = @user.books
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new params[:user]
		if @user.save
			flash[:notice] = "#{@user.username}'s account created"
			redirect_to @user
		else
			render :new
		end
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		if @user.update_attributes(params[:user])
			flash[:notice] = "#{@user.username}'s account updated"
			redirect_to @user
		else
			render :edit
		end
	end

	private
	def admin_required
		unless current_admin
			flash[:error] = "Only logged in admins can access this page"
			redirect_to books_path
		end
	end

	def login_required
		unless current_user
			flash[:error] = "Must be logged in to view this page"
			redirect_to books_path
		end
	end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def javascript(*args)
	  content_for(:head) { javascript_include_tag(*args) }
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/views/admin_sessions/new.html.erb
<% title 'Login' %>  
  
<%= form_for @admin_session, :url => admin_session_path do |f| %>  
  <%= f.error_messages %>  
  <p>  
    <%= f.label :username %><br />  
    <%= f.text_field :username %>  
  </p>  
  
  <p>  
    <%= f.label :password %><br />  
    <%= f.password_field :password %>  
  </p>  
  
  <%= f.submit "Login" %>  
<% end %>  

app/views/books/_form.html.erb
<%= form_for [@book, Review.new] do |form| %>
	<p><%= form.label :author %></p>
	<p><%= form.text_field :author %></p>

	<p><%= form.label :rating %></p>
	<p><%= form.select(:rating, [['0', 1], ['1', 2], ['2', 3], ['3', 4], ['4', 5], ['5', 6]]) %></p>

	<p><%= form.label :text, "Review" %></p>
	<p><%= form.text_area :text %></p>

	<%= form.submit "Save Review" %>
<% end %>

app/views/books/_partial.html.erb
<% for book in @books do %>
	<div>
		<h2><%= link_to(h(book.title), book_path(book)) %></h2>
		<%= image_tag book.cover_image.url(:medium), :width => "25%" %>
		<h3><%=h "by: " + book.author %></h3>
		<p><%= simple_format(truncate(book.description, :length => 50, :separator => ' ')) %></p>
	</div>
<% end %>

app/views/books/edit.html.erb
<% title "Editing #{@book.title}" %> 
<%= form_for @book, :html => { :multipart => true } do |form| %> 
  <p>
    <%= form.label :cover_image %><br/>  
    <%= form.file_field :cover_image %>
  </p> 
  <p>  
    <%= form.label :title %><br/>  
    <%= form.text_field :title %>  
  </p>  

  <p><%= form.label :author %></p>
  <p><%= form.text_field :author %></p>
  
  <p>  
    <%= form.label :description %><br/>  
    <%= form.text_area :description %>  
  </p>  
  
  <%= form.submit "Save Book" %>  
<% end %>  

app/views/books/index.html.erb
<% title "Books" %>
<%= javascript_include_tag 'endless_page' %>
<div id="books">
	<% for book in @books do %>
		<div>
			<h2><%=link_to(h(book.title), book_path(book)) %></h2>
			<%= image_tag book.cover_image.url(:medium), :width => "25%" %>
			<h3><%=h "by: " + book.author %></h3>
			<p><%= simple_format(truncate(book.description, :length => 50, :separator => ' ')) %></p>
		</div>
	<% end %>
</div>
<p id="loading">Loading more page results...</p>

<% if current_admin %>
	<p>
		Admin actions: <%= link_to "Add New Book", new_book_path %>
	</p>
<% end %>

app/views/books/new.html.erb
<% title "New Book" %> 
<%= form_for @book, :html => { :multipart => true } do |form| %> 
  <p>
    <%= form.label :cover_image %><br/>  
    <%= form.file_field :cover_image %>
  </p>  
  <p>  
    <%= form.label :title %><br/>  
    <%= form.text_field :title %>  
  </p>  

  <p><%= form.label :author %></p>
  <p><%= form.text_field :author %></p>
  
  <p>  
    <%= form.label :description %><br/>  
    <%= form.text_area :description %>  
  </p>  
  
  <%= form.submit "Save Book" %>  
<% end %>  

app/views/books/show.html.erb
<% if current_admin %>
	<p>
		Admin Actions:
		<%= link_to "Edit", edit_book_path(@book) %> |
		<%= link_to "Delete", book_path(@book), :method => :delete, :confirm => "Are you sure you want to delete #{@book.title}?" %>
	</p>
<% end %>

<% title @book.title %>  
<%=link_to(h("Back to more books"), books_path) %>


<%= image_tag @book.cover_image.url(:medium) %>
  
<h3><%=h "by: " + @book.author %></h3>
<p><%= @book.description %></p> 

<% if @reviews %>
	<h3>Reviews</h3>

	<% for review in @reviews do %>
		<p><em><%=h(review.author) %></em> <%= "Rating: " + review.rating.to_s + "/5" %></p>
		<p><%=h review.text %></p>
	<% end %>
<% end %>

<h3>Post Your Review!</h3>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body> 
    <div id="container">
      <% if current_admin %>
        <p><%= link_to "Admin Logout", admin_session_path(current_admin_session), :method => :delete %></p>
      <% else %>
        <p><%= link_to "Admin Login", new_admin_session_path %></p>
      <% end %>

      <% if current_user %>
        <%= link_to "Edit Profile", edit_user_path(:current) %> |
        <%= link_to "Logout", user_session_path(current_user_session), :method => :delete %>
      <% else %>
        <%= link_to "Register", new_user_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>

    </div>
  </body>
</html>

app/views/user_sessions/new.html.erb
<% title "Login" %>

<%= form_for @user_session, :url => user_session_path do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit "Login" %></p>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %> 
  <%= f.error_messages %>

  <p>
    <%= f.label :avatar %><br/>  
    <%= f.file_field :avatar %>
  </p> 
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Editing #{@user.username}" %> 
<%= form_for(@user) do |form| %> 
  <p>
    <%= form.label :avatar %><br/>  
    <%= form.file_field :avatar %>
  </p>  
  <p>  
    <%= form.label :email %><br/>  
    <%= form.text_field :email %>  
  </p>  

  <p><%= form.label :password %></p>
  <p><%= form.password_field :password %></p>
  
  <p>
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation %>
  </p>
  
  <%= form.submit "Save" %>  
<% end %>  

app/views/users/new.html.erb
<% title "Sign Up" %>  
<%= render "form" %>

app/views/users/show.html.erb
<% if current_user %>
	<p>
		User Actions:

	</p>
<% end %>

<% title "Welcome, " + @user.username %>  